### ISSUE TITLE
Power LED should be on by default

### ISSUE THREAD

**Issue by cednik** [Pletacka-IoT/Pletacka-board#7]
And ESP can turn it off, but by default it shoult indicate presence of the power.

**Suggestion**
![obrazek](https://user-images.githubusercontent.com/8156860/89781971-9ee72a00-db14-11ea-967c-951290c2d345.png)

**Comment by JarekParal** [comment]
There should be PWR LED used as ESP start-up indicator. Not a power indicator.

**Suggestion**
`PWR` -> `ON`
